### ISSUE TITLE
Feature: Add changelog to docs

### ISSUE THREAD

**Issue by munkm** [arfc/saltproc#105]
## Background and motivation

It looks like the changelog is associated with our newest tagged release, but I'm not sure it is easily discoverable outside of the github interface. It would be great if it showed up more clearly in our docs. 

## Description of idea

We should have a separate, easily discoverable changelog for this project that's included in our documentation. 

## Implementation details
I suggest making a separate `changelog.rst` file, and then make sure it is required that we update it when we put out a new tagged release. the changelog can then be sourced in the `index.rst` file of the docs. [by @munkm]

Checkboxes for features: 
- [x] Release notes template
- [x] Workflow to create new draft release, milestone, and release notes from the template that are all 1 minor version higher than the current release upon publishing of current release
- [x] Workflow that we can manually run to do the same as above but for micro version releases (i.e. patches and hotfixes)
- [x] Workflow to populate the draft release description with the associated release notes on that milestone when those release notes are updated
- [x] Add checkbox to the PR template that requires updating the release notes for the current milestone
- [x] Detail the new parts of the workflow in the Contributing.md document
- [x] Start a dev guide in the docs that details this as well.

The should all be in the same PR
[by @yardasol]

## Potential snags

I don't see any issues. We can have a running changelog file that gets added to every release cycle. [by @munkm]

**Comment by yardasol** [comment]
We should also add a checkbox like the following to the PR template:
```
[ ] I have recorded my changes to the changelog for the upcoming release.
```

**Comment by yardasol** [comment]
We should also add a gh-actions workflow that converts the `.rst` version of the releasenotes int markdown and populate the GitHub release note body with the resulting content.

**Comment by yardasol** [comment]
I've made some progress on this in the `doc-changelog` branch. I'd be able to finish this today if `gh` (the CLI tool) allowed release editing, but because it doesn't, I'll either have to wait for that feature to be added (I don't know how to do it myself) or come up with a hack solution which also isn't ideal.

**Comment by yardasol** [comment]
There is [an issue in the cls repo](https://github.com/cli/cli/issues/2873) about this that hasn't been touched for two years.

**Comment by yardasol** [comment]
Update: while the gh cli tool won't do it, I can use the github REST API directly to make edits to the release notes. I was actually trying to do this in the first place but it wasn't working because the URL I was giving it to make the PATCH request ended in `saltproc/releases/tags/{tag}`. However, the [documentation](https://docs.github.com/en/rest/reference/releases#update-a-release) explicitly states that the URL needs to have the form `saltproc/releases/{release_id}`. Will get this implemented tomorrow hopefully.

**Comment by yardasol** [comment]
Checkboxes for features:
- [ ] Release notes template
- [ ] Workflow to create new draft release, milestone, and release notes from the template that are all 1 minor version higher than the current release upon publishing of current release
- [ ] Workflow that we can manually run to do the same as above but for micro version releases (i.e. patches and hotfixes)
- [ ] Workflow to populate the draft release description with the associated release notes on that milestone when those release notes are updated
- [ ] Add checkbox to the PR template that requires updating the release notes for the current milestone

**Comment by yardasol** [comment]
I added the checkboxes to the main body of the issue and clarified who wrote what just so we can keep track of everything better
